# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MB80WWNper7KoUkHzyb0bjiN3ma4TBEI
"""

import pandas as pd
import numpy as np
import re


# Helpers robustos

def _to_float(x, default=0.0):
    try:
        return float(x)
    except Exception:
        return default


def _to_int(x, default=0):
    try:
        return int(float(x))
    except Exception:
        return default


def build_features(data: dict, stats: dict, features_list=None) -> pd.DataFrame:
    """
    Construye features listas para el modelo a partir de un dict (request JSON).
    - data: dict con las variables de entrada
    - stats: dict precalculado (global_mean, artist_mean, genre_mean)
    - features_list: lista de columnas esperadas por el modelo
    """


    # 0. Crear dataframe base

    df = pd.DataFrame([data]).copy()


    # 1. Tipos y defaults seguros

    numeric_cols = [
        "danceability", "energy", "loudness", "valence",
        "speechiness", "instrumentalness", "liveness",
        "acousticness", "duration_ms", "key", "mode"
    ]

    for col in numeric_cols:
        df[col] = _to_float(data.get(col, 0.0))

    df["explicit"] = _to_int(data.get("explicit", 0))


    # 2. Texto (robusto)

    name = str(data.get("track_name", "") or "").lower()
    artists = str(data.get("artists", "") or "")
    album = str(data.get("album_name", "") or "").lower()

    df["has_feat"]  = int(bool(re.search(r'feat\.|ft\.| x ', name)))
    df["has_remix"] = int(bool(re.search(r'remix|edit|version|remaster', name)))
    df["has_live"]  = int(bool(re.search(r'live|en vivo|ao vivo', name)))

    df["track_name_len"] = len(name)
    df["track_words"]    = len(name.split()) if name else 0
    df["has_paren"]      = int(("(" in name) or ("[" in name))

    df["n_artists"]       = artists.count(";") + 1 if artists else 1
    df["artist_name_len"] = len(artists)

    df["album_is_single"] = int("single" in album)
    df["album_name_len"]  = len(album)


    # 3. Stats precalculadas

    artist = str(data.get("artists", "") or "")
    genre  = str(data.get("track_genre", "") or "")

    global_mean = float(stats.get("global_mean", 50))

    df["artist_mean"] = stats.get("artist_mean", {}).get(artist, global_mean)
    df["genre_mean"]  = stats.get("genre_mean", {}).get(genre, global_mean)


    # 4. Audio interactions (core signal)

    df["loudness_energy"]   = df["loudness"] * df["energy"]
    df["dance_valence"]     = df["danceability"] * df["valence"]
    df["speech_instrument"] = df["speechiness"] + df["instrumentalness"]
    df["liveness_explicit"] = df["liveness"] * df["explicit"]

    df["energy_valence"]     = df["energy"] * df["valence"]
    df["dance_energy"]       = df["danceability"] * df["energy"]
    df["acoustic_instrument"] = df["acousticness"] * df["instrumentalness"]

    duration = df["duration_ms"].iloc[0]

    df["duration_min"]   = duration / 60000.0
    df["is_short_track"] = int(duration < 120000)
    df["is_long_track"]  = int(duration > 300000)

    df["loudness_norm"] = (df["loudness"] + 60.0) / 60.0

    df["key_mode"] = df["key"].astype(float) * 2 + df["mode"].astype(float)


    # 5. Derivadas clave

    df["artist_vs_genre"] = df["artist_mean"] - df["genre_mean"]
    df["artist_rel_pop"]  = df["artist_mean"] / (global_mean + 1e-6)


    # 6. Limpieza (quitar texto original)

    DROP_COLS = ["track_id", "track_name", "album_name", "artists", "track_genre"]
    df = df.drop(columns=[c for c in DROP_COLS if c in df.columns], errors="ignore")


    # 7. Alinear con modelo

    if features_list is not None:
        df = df.reindex(columns=features_list, fill_value=0)


    # 8. Seguridad final (sin NaN / inf)

    df = df.replace([np.inf, -np.inf], 0).fillna(0)
    df = df.select_dtypes(include=[np.number, "bool"])

    return df